import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className='logo'>Appleforum</Link>
          <Link href="/list">List</Link>
          {
            session ? 
            <>
              <LogoutBtn />
              <span>{session.user.name}</span>
            </> : <LoginBtn />
          }
        </div>
        {children}
      </body>
    </html>
  )
}
